# Generated by Django 5.2.1 on 2025-05-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('birth', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
