# Generated by Django 5.2.1 on 2025-05-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_biodata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='mobileno',
            new_name='mobile_no',
        ),
    ]
