# Generated by Django 5.2.1 on 2025-05-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_rename_mobileno_biodata_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
