# Generated by Django 5.2.1 on 2025-05-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_alter_biodata_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('credits', models.IntegerField()),
            ],
        ),
    ]
