# Generated by Django 5.2.1 on 2025-05-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='rollno',
        ),
    ]
