# Generated by Django 5.2.1 on 2025-05-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_rename_description_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rollno',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='gender',
            new_name='stream',
        ),
    ]
