# Generated by Django 5.2.1 on 2025-05-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_rename_rollno_course_age_rename_gender_course_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
